# Generated by Django 3.2 on 2023-02-06 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='name',
        ),
        migrations.RemoveField(
            model_name='advert',
            name='tags',
        ),
        migrations.AddField(
            model_name='advert',
            name='ad_url',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AddField(
            model_name='advert',
            name='image',
            field=models.ImageField(default=' ', upload_to='image/'),
        ),
    ]
