# Generated by Django 3.2 on 2023-02-06 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20230206_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='name',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='advert',
            name='tags',
            field=models.ManyToManyField(to='myapp.Tag'),
        ),
    ]
